name: Front Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - develop
    paths:
      - 'front/**'  # Se déclenche uniquement si des fichiers dans 'front' sont modifiés
  pull_request:
    branches:
      - main
    paths:
      - 'front/**'  # Se déclenche uniquement si des fichiers dans 'front' sont modifiés

jobs:
  # Job 1 : Tests
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        working-directory: front
        run: npm ci

      - name: Run tests
        working-directory: front
        run: npx ng test --browsers=ChromeHeadless --watch=false --code-coverage

      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
            name: coverage-report
            path: front/coverage

  # Job 2 : SonarCloud
  sonar:
    runs-on: ubuntu-latest
    needs: tests  # Ce job ne s'exécute que si les tests réussissent
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run SonarCloud analysis
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: ./front

  # Job 3 : Docker
  docker:
    runs-on: ubuntu-latest
    needs: sonar  # Ce job ne s'exécute que si SonarCloud réussit
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push front Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./front
          file: ./front/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/bobapp-front:latest